### ISSUE TITLE
gnosis-withdrawal-devnet-4 testing tracker

### ISSUE THREAD

**Issue by dapplion** [gnosischain/consensus-deployment-ansible#67]
While Hive tests are being developed, @filoozom and I will do manual testing on devnet-4. The list of items is not long so if properly documented should give confidence to clients of readiness.

**Withdrawals**
- [ ] Send BLS credential changes to some portion of genesis validators
- [x] Assert partial withdrawals happening correctly
- [ ] Send VoluntaryExit for some portion of genesis validators with BLS credentials
- [ ] Assert full withdrawals happening correctly
- [x] Drain deposit contract of all funds (with `stealFrom`)
- [x] Assert backlog of withdrawals accumulates
  - Check that `SBCDepositContract.numberOfFailedWithdrawals() > 0`
  - Query some indexes of `SBCDepositContract.failedWithdrawals(i)` and assert withdraw data matches that of blocks
- [x] Refund deposit contract
- [x] Assert partial withdrawals are happening correctly again
- [x] Assert failedWithdrawals queue is being cleared (check that `failedWithdrawalsPointer` > 0` and eventually `numberOfFailedWithdrawals == failedWithdrawalsPointer`

**EIP-3860**
Limits the size of deployed contracts and makes deployments a bit more expensive
- [ ] Attempt to deploy a contract above the limit and expect failure

CC: @filoozom

**Comment by dapplion** [comment]
Testing automated with https://github.com/gnosischain/deposit-contract/pull/40

**Comment by dapplion** [comment]
Completed
